### ISSUE TITLE
omr-admin service KO

### ISSUE THREAD

**Issue by kevinpato72** [Ysurac/openmptcprouter#2885]
## Expected Behavior

omr-admin service should be in running mode

## Current Behavior

omr-admin service try to start 5 times but it fails :
```
Jul 18 18:39:48 mwc278 systemd[1]: Started OMR-Admin.
Jul 18 18:39:49 mwc278 omr-admin.py[26021]: Traceback (most recent call last):
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:   File "/usr/local/bin/omr-admin.py", line 39, in <module>
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:     from fastapi import Depends, FastAPI, HTTPException, Security, Query, Request
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/__init__.py", line 7, in <module>
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:     from .applications import FastAPI as FastAPI
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 16, in <module>
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:     from fastapi import routing
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 22, in <module>
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:     from fastapi import params
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/params.py", line 8, in <module>
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:     from ._compat import PYDANTIC_V2, Undefined
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:   File "/usr/local/lib/python3.9/dist-packages/fastapi/_compat.py", line 297, in <module>
Jul 18 18:39:49 mwc278 omr-admin.py[26021]:     from pydantic.networks import (  # type: ignore[no-redef]
Jul 18 18:39:49 mwc278 omr-admin.py[26021]: ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks' (/usr/local/lib/python3.9/dist-packages/pydantic/networks.cpython-39-x86_64-linux-gnu.so)
Jul 18 18:39:49 mwc278 systemd[1]: omr-admin.service: Main process exited, code=exited, status=1/FAILURE
Jul 18 18:39:49 mwc278 systemd[1]: omr-admin.service: Failed with result 'exit-code'.
Jul 18 18:39:49 mwc278 systemd[1]: omr-admin.service: Scheduled restart job, restart counter is at 5.
Jul 18 18:39:49 mwc278 systemd[1]: Stopped OMR-Admin.
```

## Possible Solution

Problem appears since July, 11th. I think it caused by the new version of package :
        "upgrade omr-vps-admin:all 0.3+20220827 0.3+20230709",
        "upgrade python3-wsproto:all 0.15.0-3 0.15.0-3"

## Steps to Reproduce the Problem

  1. Upgrade omr-vps-admin package ? 
  2. Restart omr-admin service

## Context (Environment)

MilkyWan VM on Debian 11, up-to-date.

## Specifications

  - OpenMPTCProuter version: v0.59.1-5.4 r0+16594-ce92de8c8c
  - OpenMPTCProuter VPS version: 0.1028 
  - OpenMPTCProuter VPS provider: Milkywan
  - OpenMPTCProuter platform: x86_64 
  - Country: FR

**Comment by Ysurac** [comment]
I updated VPS script, can you try to run it again: ```wget -O - https://www.openmptcprouter.com/server/debian-x86_64.sh | sh```

**Comment by kevinpato72** [comment]
Problem solved, thanks !
