### ISSUE TITLE
omr-admin runs into an error

### ISSUE THREAD

**Issue by thejoef** [Ysurac/openmptcprouter#3018]
## Current Behavior

omr-admin runs into an error, no settings are loaded from vps
```shell
● omr-admin.service - OMR-Admin
     Loaded: loaded (/lib/systemd/system/omr-admin.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-11-04 13:32:14 CET; 1min 7s ago
   Main PID: 433 (python3)
      Tasks: 7 (limit: 2315)
     Memory: 77.1M
        CPU: 2.886s
     CGroup: /system.slice/omr-admin.service
             └─433 python3 /usr/local/bin/omr-admin.py

Nov 04 13:33:21 mtcprouter omr-admin.py[433]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 274, in app
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:     raw_response = await run_endpoint_function(
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:     return await dependant.call(**values)
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:   File "/usr/local/bin/omr-admin.py", line 1714, in config
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:     ss_go_tx = ss_go_txrx['downlinkBytes']
Nov 04 13:33:21 mtcprouter omr-admin.py[433]:                ~~~~~~~~~~^^^^^^^^^^^^^^^^^
Nov 04 13:33:21 mtcprouter omr-admin.py[433]: TypeError: 'int' object is not subscriptable
``` 
```shell
Nov 04 13:02:07 mtcprouter omr-admin.py[432]: ERROR:    Exception in ASGI application
Nov 04 13:02:07 mtcprouter omr-admin.py[432]: Traceback (most recent call last):
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 384, in run_asgi
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     result = await app(self.scope, self.receive, self.send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     return await self.app(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 1106, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await super().__call__(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 122, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.middleware_stack(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     raise exc
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.app(scope, receive, _send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     raise exc
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.app(scope, receive, sender)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     raise e
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.app(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 718, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await route.handle(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 276, in handle
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.app(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 66, in app
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     response = await func(request)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:                ^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 274, in app
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     raw_response = await run_endpoint_function(
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     return await dependant.call(**values)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/bin/omr-admin.py", line 1714, in config
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     ss_go_tx = ss_go_txrx['downlinkBytes']
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:                ~~~~~~~~~~^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]: TypeError: 'int' object is not subscriptable
Nov 04 13:02:07 mtcprouter omr-admin.py[432]: ERROR:    Exception in ASGI application
Nov 04 13:02:07 mtcprouter omr-admin.py[432]: Traceback (most recent call last):
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 384, in run_asgi
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     result = await app(self.scope, self.receive, self.send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     return await self.app(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 1106, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await super().__call__(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 122, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.middleware_stack(scope, receive, send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     raise exc
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.app(scope, receive, _send)
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     raise exc
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
Nov 04 13:02:07 mtcprouter omr-admin.py[432]:     await self.app(scope, receive, sender)


``` 

## Specifications

  - Debian 12.2
  - OpenMPTCProuter version: openmptcprouter-v0.60beta1-6.1-r0+24041-74e7f8ebbd-x86-64-generic-ext4-combined.raw
  - OpenMPTCProuter VPS version: Server 0.1029-test
  - OpenMPTCProuter VPS provider:
  - OpenMPTCProuter platform: x86_64
  - Country:

**Comment by thejoef** [comment]
Now is typeError: argument of type 'int' is not iterable
```shell
root@mtcprouter:/home/mtcprouter# systemctl status omr-admin
● omr-admin.service - OMR-Admin
     Loaded: loaded (/lib/systemd/system/omr-admin.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-11-04 22:00:56 CET; 1min 54s ago
   Main PID: 128891 (python3)
      Tasks: 8 (limit: 2315)
     Memory: 68.5M
        CPU: 2.472s
     CGroup: /system.slice/omr-admin.service
             └─128891 python3 /usr/local/bin/omr-admin.py

Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 274, in app
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:     raw_response = await run_endpoint_function(
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:     return await dependant.call(**values)
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:   File "/usr/local/bin/omr-admin.py", line 1714, in config
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:     if 'downlinkBytes' in ss_go_txrx:
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 04 22:02:43 mtcprouter omr-admin.py[128891]: TypeError: argument of type 'int' is not iterable
```
